name: Scrape Executive Orders - OLD

on:

  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main  # Run on push to main branch for initial setup

permissions:
  contents: write  # Required for pushing changes

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scraper
      run: |
        cd /home/runner/work/trumporders
        python scrape_historical_orders.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add orders/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update executive orders" && git push)