name: Run UCSB Scraper Manually

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape_ucsb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Or the version specified in your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run UCSB Scraper
        run: python src/presidency_ucsb.py
